set(STM32_FAMILY "G4")

set(EEPROM_PORTING_DIR ${CMAKE_CURRENT_SOURCE_DIR}/X-CUBE-EEPROM/Porting/STM32${STM32_FAMILY})
if(NOT EXISTS ${EEPROM_PORTING_DIR})
    message(FATAL_ERROR "No support for: STM32${STM32_FAMILY}")
endif()

set(EEPROM_LIBRARY_INC 
    ${CMAKE_CURRENT_SOURCE_DIR}/Inc
    ${CMAKE_CURRENT_SOURCE_DIR}/X-CUBE-EEPROM/Core
    ${EEPROM_PORTING_DIR}
)

set(EEPROM_LIBRARY_SRC
    ${CMAKE_CURRENT_SOURCE_DIR}/X-CUBE-EEPROM/Core/eeprom_emul.c
    ${EEPROM_PORTING_DIR}/flash_interface.c
)

add_library(EEPROM_LIBRARY INTERFACE)
target_include_directories(EEPROM_LIBRARY INTERFACE ${EEPROM_LIBRARY_INC})
target_sources(EEPROM_LIBRARY PUBLIC ${EEPROM_LIBRARY_SRC})
